service: boilerplate
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: get
          cors: true
          integration: lambda-proxy
      - http:
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules:
      forceExclude:
        - aws-sdk

  serverless-offline:
    useChildProcesses: true
