import { QuizQuestion } from "../index";

const question: QuizQuestion = {
  "1": {
    type: "whole",
    word: "",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "2": {
    type: "split",
    choices: ["der"],
    word: "Je",
    completeWord: "Jeder",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "3": {
    type: "whole",
    word: "kennt",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "4": {
    type: "split",
    choices: ["ie"],
    word: "s",
    completeWord: "sie",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 2,
  },
  "5": {
    type: "whole",
    word: "keiner",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "6": {
    type: "split",
    choices: ["det"],
    word: "re",
    completeWord: "redet",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "7": {
    type: "whole",
    word: "darüber",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "8": {
    type: "split",
    choices: ["bei"],
    word: "Da",
    completeWord: "Dabei",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "9": {
    type: "whole",
    word: "ist",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "10": {
    type: "split",
    choices: ["gst"],
    word: "An",
    completeWord: "Angst",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "11": {
    type: "whole",
    word: "unser",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "12": {
    type: "split",
    choices: ["und"],
    word: "Fre",
    completeWord: "Freund",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 3,
  },
  "13": {
    type: "whole",
    word: "ein",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "14": {
    type: "split",
    choices: ["chanismus"],
    word: "Schutzme",
    completeWord: "Schutzmechanismus",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 9,
  },
  "15": {
    type: "whole",
    word: "der",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "16": {
    type: "split",
    choices: ["ser"],
    word: "un",
    completeWord: "unser",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "17": {
    type: "whole",
    word: "Leben",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "18": {
    type: "split",
    choices: ["ten"],
    word: "ret",
    completeWord: "retten",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "19": {
    type: "whole",
    word: "soll",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "20": {
    type: "split",
    choices: ["ch"],
    word: "Do",
    completeWord: "Doch",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "21": {
    type: "whole",
    word: "was",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "22": {
    type: "split",
    choices: ["un"],
    word: "t",
    completeWord: "tun",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 2,
  },
  "23": {
    type: "whole",
    word: "wenn",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "24": {
    type: "split",
    choices: ["ie"],
    word: "d",
    completeWord: "die",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "25": {
    type: "whole",
    word: "Angst",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "26": {
    type: "split",
    choices: ["ächtig"],
    word: "überm",
    completeWord: "übermächtig",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 6,
  },
  "27": {
    type: "whole",
    word: "wird",
    returnedWordBegin: "",
    returnedWordEnd: "?",
  },
  "28": {
    type: "split",
    choices: ["gst"],
    word: "An",
    completeWord: "Angst",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "29": {
    type: "whole",
    word: "ist",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "30": {
    type: "split",
    choices: ["ne"],
    word: "ei",
    completeWord: "eine",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "31": {
    type: "whole",
    word: "gute",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "32": {
    type: "split",
    choices: ["che"],
    word: "Sa",
    completeWord: "Sache",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 3,
  },
  "33": {
    type: "whole",
    word: "und",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "34": {
    type: "split",
    choices: ["ie"],
    word: "s",
    completeWord: "sie",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "35": {
    type: "whole",
    word: "ist",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "36": {
    type: "split",
    choices: ["snotwendig"],
    word: "überleben",
    completeWord: "überlebensnotwendig",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 10,
  },
  "37": {
    type: "whole",
    word: "Das",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "38": {
    type: "split",
    choices: ["gte"],
    word: "sa",
    completeWord: "sagte",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "39": {
    type: "whole",
    word: "Dr",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "40": {
    type: "split",
    choices: ["ulz"],
    word: "Sch",
    completeWord: "Schulz",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 3,
  },
  "41": {
    type: "whole",
    word: "mein",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "42": {
    type: "split",
    choices: ["lempner"],
    word: "Seelenk",
    completeWord: "Seelenklempner",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 7,
  },
  "43": {
    type: "whole",
    word: "Klingt",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "44": {
    type: "split",
    choices: ["ch"],
    word: "do",
    completeWord: "doch",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "45": {
    type: "whole",
    word: "gut",
    returnedWordBegin: "",
    returnedWordEnd: ",",
  },
  "46": {
    type: "split",
    choices: ["er"],
    word: "od",
    completeWord: "oder",
    returnedWordBegin: "",
    returnedWordEnd: "?",
    replacedWordLength: 2,
  },
  "47": {
    type: "whole",
    word: "Doch",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "48": {
    type: "split",
    choices: ["nn"],
    word: "da",
    completeWord: "dann",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "49": {
    type: "whole",
    word: "meinte",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "50": {
    type: "split",
    choices: ["r"],
    word: "e",
    completeWord: "er",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "51": {
    type: "whole",
    word: "noch",
    returnedWordBegin: "",
    returnedWordEnd: ":",
  },
  "52": {
    type: "split",
    choices: ["gst"],
    word: "An",
    completeWord: "Angst",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "53": {
    type: "whole",
    word: "käme",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "54": {
    type: "split",
    choices: ["om"],
    word: "v",
    completeWord: "vom",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "55": {
    type: "whole",
    word: "lateinischen",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "56": {
    type: "split",
    choices: ["rt"],
    word: "Wo",
    completeWord: "Wort",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "57": {
    type: "whole",
    word: "angere",
    returnedWordBegin: "„",
    returnedWordEnd: "“",
  },
  "58": {
    type: "split",
    choices: ["nd"],
    word: "u",
    completeWord: "und",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "59": {
    type: "whole",
    word: "das",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "60": {
    type: "split",
    choices: ["rde"],
    word: "wü",
    completeWord: "würde",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "61": {
    type: "whole",
    word: "würgen",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "62": {
    type: "split",
    choices: ["er"],
    word: "od",
    completeWord: "oder",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "63": {
    type: "whole",
    word: "die",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "64": {
    type: "split",
    choices: ["hle"],
    word: "Ke",
    completeWord: "Kehle",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "65": {
    type: "whole",
    word: "zuschnüren",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "66": {
    type: "split",
    choices: ["uten"],
    word: "bede",
    completeWord: "bedeuten",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 4,
  },
  "67": {
    type: "whole",
    word: "Klingt",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "68": {
    type: "split",
    choices: ["ar"],
    word: "g",
    completeWord: "gar",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "69": {
    type: "whole",
    word: "nicht",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "70": {
    type: "split",
    choices: ["hr"],
    word: "me",
    completeWord: "mehr",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "71": {
    type: "whole",
    word: "so",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "72": {
    type: "split",
    choices: ["dlich"],
    word: "freun",
    completeWord: "freundlich",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 5,
  },
  "73": {
    type: "whole",
    word: "oder",
    returnedWordBegin: "",
    returnedWordEnd: "?",
  },
  "74": {
    type: "split",
    choices: ["er"],
    word: "Ab",
    completeWord: "Aber",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "75": {
    type: "whole",
    word: "er",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "76": {
    type: "split",
    choices: ["st"],
    word: "i",
    completeWord: "ist",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "77": {
    type: "whole",
    word: "der",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "78": {
    type: "split",
    choices: ["erte"],
    word: "Exp",
    completeWord: "Experte",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 4,
  },
  "79": {
    type: "whole",
    word: "er",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "80": {
    type: "split",
    choices: ["ss"],
    word: "mu",
    completeWord: "muss",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "81": {
    type: "whole",
    word: "es",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "82": {
    type: "split",
    choices: ["sen"],
    word: "wis",
    completeWord: "wissen",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 3,
  },
  "83": {
    type: "whole",
    word: "Wie",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "84": {
    type: "split",
    choices: ["ch"],
    word: "si",
    completeWord: "sich",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "85": {
    type: "whole",
    word: "die",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "86": {
    type: "split",
    choices: ["gst"],
    word: "An",
    completeWord: "Angst",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "87": {
    type: "whole",
    word: "bei",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "88": {
    type: "split",
    choices: ["ir"],
    word: "m",
    completeWord: "mir",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "89": {
    type: "whole",
    word: "äußert",
    returnedWordBegin: "",
    returnedWordEnd: "?",
  },
  "90": {
    type: "split",
    choices: ["rje"],
    word: "Her",
    completeWord: "Herrje",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 3,
  },
  "91": {
    type: "whole",
    word: "wo",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "92": {
    type: "split",
    choices: ["ll"],
    word: "so",
    completeWord: "soll",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "93": {
    type: "whole",
    word: "ich",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "94": {
    type: "split",
    choices: ["ngen"],
    word: "anfa",
    completeWord: "anfangen",
    returnedWordBegin: "",
    returnedWordEnd: "?",
    replacedWordLength: 4,
  },
  "95": {
    type: "whole",
    word: "Vor",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "96": {
    type: "split",
    choices: ["der"],
    word: "je",
    completeWord: "jeder",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "97": {
    type: "whole",
    word: "Prüfung",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "98": {
    type: "split",
    choices: ["be"],
    word: "ha",
    completeWord: "habe",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "99": {
    type: "whole",
    word: "ich",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "100": {
    type: "split",
    choices: ["nen"],
    word: "ei",
    completeWord: "einen",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "101": {
    type: "whole",
    word: "Kloß",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "102": {
    type: "split",
    choices: ["m"],
    word: "i",
    completeWord: "im",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "103": {
    type: "whole",
    word: "Hals",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "104": {
    type: "split",
    choices: ["a"],
    word: "D",
    completeWord: "Da",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "105": {
    type: "whole",
    word: "passt",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "106": {
    type: "split",
    choices: ["as"],
    word: "d",
    completeWord: "das",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "107": {
    type: "whole",
    word: "mit",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "108": {
    type: "split",
    choices: ["er"],
    word: "d",
    completeWord: "der",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "109": {
    type: "whole",
    word: "Kehle",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "110": {
    type: "split",
    choices: ["a"],
    word: "j",
    completeWord: "ja",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "111": {
    type: "whole",
    word: "ganz",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "112": {
    type: "split",
    choices: ["ut"],
    word: "g",
    completeWord: "gut",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 2,
  },
  "113": {
    type: "whole",
    word: "Dann",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "114": {
    type: "split",
    choices: ["rasen"],
    word: "Herz",
    completeWord: "Herzrasen",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 5,
  },
  "115": {
    type: "whole",
    word: "Ich",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "116": {
    type: "split",
    choices: ["che"],
    word: "ma",
    completeWord: "mache",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "117": {
    type: "whole",
    word: "mir",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "118": {
    type: "split",
    choices: [""],
    word: "",
    completeWord: "",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 0,
  },
  "119": {
    type: "whole",
    word: "fast",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "120": {
    type: "split",
    choices: ["or"],
    word: "v",
    completeWord: "vor",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "121": {
    type: "whole",
    word: "Angst",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "122": {
    type: "split",
    choices: ["n"],
    word: "i",
    completeWord: "in",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "123": {
    type: "whole",
    word: "die",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "124": {
    type: "split",
    choices: ["sen"],
    word: "Ho",
    completeWord: "Hosen",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 3,
  },
  "125": {
    type: "whole",
    word: "Wie",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "126": {
    type: "split",
    choices: ["ft"],
    word: "o",
    completeWord: "oft",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "127": {
    type: "whole",
    word: "ich",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "128": {
    type: "split",
    choices: ["or"],
    word: "v",
    completeWord: "vor",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "129": {
    type: "whole",
    word: "den",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "130": {
    type: "split",
    choices: ["ungen"],
    word: "Prüf",
    completeWord: "Prüfungen",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 5,
  },
  "131": {
    type: "whole",
    word: "aufs",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "132": {
    type: "split",
    choices: ["lo"],
    word: "K",
    completeWord: "Klo",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "133": {
    type: "whole",
    word: "renne",
    returnedWordBegin: "",
    returnedWordEnd: ",",
  },
  "134": {
    type: "split",
    choices: ["ähle"],
    word: "erz",
    completeWord: "erzähle",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "135": {
    type: "whole",
    word: "ich",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "136": {
    type: "split",
    choices: ["m"],
    word: "a",
    completeWord: "am",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "137": {
    type: "whole",
    word: "besten",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "138": {
    type: "split",
    choices: ["st"],
    word: "er",
    completeWord: "erst",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "139": {
    type: "whole",
    word: "gar",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "140": {
    type: "split",
    choices: ["cht"],
    word: "ni",
    completeWord: "nicht",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 3,
  },
  "141": {
    type: "whole",
    word: "Dr",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "142": {
    type: "split",
    choices: ["ulz"],
    word: "Sch",
    completeWord: "Schulz",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "143": {
    type: "whole",
    word: "sagte",
    returnedWordBegin: "",
    returnedWordEnd: ",",
  },
  "144": {
    type: "split",
    choices: ["ss"],
    word: "da",
    completeWord: "dass",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "145": {
    type: "whole",
    word: "ich",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "146": {
    type: "split",
    choices: ["ie"],
    word: "d",
    completeWord: "die",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "147": {
    type: "whole",
    word: "Prüfung",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "148": {
    type: "split",
    choices: ["ls"],
    word: "a",
    completeWord: "als",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "149": {
    type: "whole",
    word: "derart",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "150": {
    type: "split",
    choices: ["hlich"],
    word: "bedro",
    completeWord: "bedrohlich",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 5,
  },
  "151": {
    type: "whole",
    word: "ansähe",
    returnedWordBegin: "",
    returnedWordEnd: ",",
  },
  "152": {
    type: "split",
    choices: ["ss"],
    word: "da",
    completeWord: "dass",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "153": {
    type: "whole",
    word: "mein",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "154": {
    type: "split",
    choices: ["per"],
    word: "Kör",
    completeWord: "Körper",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "155": {
    type: "whole",
    word: "sich",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "156": {
    type: "split",
    choices: ["uf"],
    word: "a",
    completeWord: "auf",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "157": {
    type: "whole",
    word: "Flucht",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "158": {
    type: "split",
    choices: ["telle"],
    word: "eins",
    completeWord: "einstelle",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 5,
  },
  "159": {
    type: "whole",
    word: "Ein",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "160": {
    type: "split",
    choices: ["lter"],
    word: "ura",
    completeWord: "uralter",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "161": {
    type: "whole",
    word: "Mechanismus",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "162": {
    type: "split",
    choices: ["her"],
    word: "Da",
    completeWord: "Daher",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "163": {
    type: "whole",
    word: "pumpte",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "164": {
    type: "split",
    choices: ["as"],
    word: "d",
    completeWord: "das",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "165": {
    type: "whole",
    word: "Herz",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "166": {
    type: "split",
    choices: ["nell"],
    word: "sch",
    completeWord: "schnell",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "167": {
    type: "whole",
    word: "das",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "168": {
    type: "split",
    choices: ["ut"],
    word: "Bl",
    completeWord: "Blut",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "169": {
    type: "whole",
    word: "in",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "170": {
    type: "split",
    choices: ["ie"],
    word: "d",
    completeWord: "die",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "171": {
    type: "whole",
    word: "angespannten",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "172": {
    type: "split",
    choices: ["keln"],
    word: "Mus",
    completeWord: "Muskeln",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 4,
  },
  "173": {
    type: "whole",
    word: "Und",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "174": {
    type: "split",
    choices: ["m"],
    word: "u",
    completeWord: "um",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "175": {
    type: "whole",
    word: "möglichst",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "176": {
    type: "split",
    choices: ["nell"],
    word: "sch",
    completeWord: "schnell",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "177": {
    type: "whole",
    word: "flüchten",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "178": {
    type: "split",
    choices: ["u"],
    word: "z",
    completeWord: "zu",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "179": {
    type: "whole",
    word: "können",
    returnedWordBegin: "",
    returnedWordEnd: ",",
  },
  "180": {
    type: "split",
    choices: ["rde"],
    word: "wü",
    completeWord: "würde",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "181": {
    type: "whole",
    word: "der",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "182": {
    type: "split",
    choices: ["per"],
    word: "Kör",
    completeWord: "Körper",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "183": {
    type: "whole",
    word: "schnell",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "184": {
    type: "split",
    choices: ["ch"],
    word: "no",
    completeWord: "noch",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "185": {
    type: "whole",
    word: "alles",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "186": {
    type: "split",
    choices: ["erden"],
    word: "losw",
    completeWord: "loswerden",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 5,
  },
  "187": {
    type: "whole",
    word: "wollen",
    returnedWordBegin: "",
    returnedWordEnd: ",",
  },
  "188": {
    type: "split",
    choices: ["as"],
    word: "w",
    completeWord: "was",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "189": {
    type: "whole",
    word: "er",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "190": {
    type: "split",
    choices: ["cht"],
    word: "ni",
    completeWord: "nicht",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "191": {
    type: "whole",
    word: "unbedingt",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "192": {
    type: "split",
    choices: ["hte.."],
    word: "bräuc",
    completeWord: "bräuchte..",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 5,
  },
  "193": {
    type: "whole",
    word: "",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  title: "Keine Panik!",
  intro: "Angst und Panik.",
  rank: "advanced",
  id: 1,
};

export default question;
