import { QuizQuestion } from "../index";

const question: QuizQuestion = {
  "1": {
    type: "whole",
    word: "Zu",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "2": {
    type: "split",
    choices: ["nig"],
    word: "we",
    completeWord: "wenig",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "3": {
    type: "whole",
    word: "oder",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "4": {
    type: "split",
    choices: ["u"],
    word: "z",
    completeWord: "zu",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "5": {
    type: "whole",
    word: "viel",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "6": {
    type: "split",
    choices: ["lz"],
    word: "Sa",
    completeWord: "Salz",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "7": {
    type: "whole",
    word: "lassen",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "8": {
    type: "split",
    choices: ["ie"],
    word: "d",
    completeWord: "die",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "9": {
    type: "whole",
    word: "Geschmacksnerven",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "10": {
    type: "split",
    choices: ["lieren"],
    word: "rebel",
    completeWord: "rebellieren",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 6,
  },
  "11": {
    type: "whole",
    word: "Auch",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "12": {
    type: "split",
    choices: ["ie"],
    word: "d",
    completeWord: "die",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "13": {
    type: "whole",
    word: "deutsche",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "14": {
    type: "split",
    choices: ["ache"],
    word: "Spr",
    completeWord: "Sprache",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "15": {
    type: "whole",
    word: "kommt",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "16": {
    type: "split",
    choices: ["cht"],
    word: "ni",
    completeWord: "nicht",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "17": {
    type: "whole",
    word: "ohne",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "18": {
    type: "split",
    choices: ["s"],
    word: "e",
    completeWord: "es",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "19": {
    type: "whole",
    word: "aus",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "20": {
    type: "split",
    choices: ["as"],
    word: "D",
    completeWord: "Das",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "21": {
    type: "whole",
    word: "Mineral",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "22": {
    type: "split",
    choices: ["st"],
    word: "i",
    completeWord: "ist",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "23": {
    type: "whole",
    word: "eben",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "24": {
    type: "split",
    choices: ["as"],
    word: "d",
    completeWord: "das",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "25": {
    type: "whole",
    word: "Salz",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "26": {
    type: "split",
    choices: ["n"],
    word: "i",
    completeWord: "in",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "27": {
    type: "whole",
    word: "der",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "28": {
    type: "split",
    choices: ["ppe"],
    word: "Su",
    completeWord: "Suppe",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 3,
  },
  "29": {
    type: "whole",
    word: "Speisesalz",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "30": {
    type: "split",
    choices: ["so"],
    word: "al",
    completeWord: "also",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "31": {
    type: "whole",
    word: "Natriumchlorid",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "32": {
    type: "split",
    choices: ["mmt"],
    word: "ko",
    completeWord: "kommt",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "33": {
    type: "whole",
    word: "entweder",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "34": {
    type: "split",
    choices: ["us"],
    word: "a",
    completeWord: "aus",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "35": {
    type: "whole",
    word: "den",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "36": {
    type: "split",
    choices: ["fen"],
    word: "Tie",
    completeWord: "Tiefen",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "37": {
    type: "whole",
    word: "der",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "38": {
    type: "split",
    choices: ["de"],
    word: "Er",
    completeWord: "Erde",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "39": {
    type: "whole",
    word: "oder",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "40": {
    type: "split",
    choices: ["rd"],
    word: "wi",
    completeWord: "wird",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "41": {
    type: "whole",
    word: "aus",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "42": {
    type: "split",
    choices: ["em"],
    word: "d",
    completeWord: "dem",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "43": {
    type: "whole",
    word: "Meer",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "44": {
    type: "split",
    choices: ["nnen"],
    word: "gewo",
    completeWord: "gewonnen",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 4,
  },
  "45": {
    type: "whole",
    word: "Streng",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "46": {
    type: "split",
    choices: ["mmen"],
    word: "geno",
    completeWord: "genommen",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "47": {
    type: "whole",
    word: "handelt",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "48": {
    type: "split",
    choices: ["s"],
    word: "e",
    completeWord: "es",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "49": {
    type: "whole",
    word: "sich",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "50": {
    type: "split",
    choices: ["ei"],
    word: "b",
    completeWord: "bei",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "51": {
    type: "whole",
    word: "Salz",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "52": {
    type: "split",
    choices: ["cht"],
    word: "ni",
    completeWord: "nicht",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "53": {
    type: "whole",
    word: "um",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "54": {
    type: "split",
    choices: ["in"],
    word: "e",
    completeWord: "ein",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "55": {
    type: "whole",
    word: "Gewürz",
    returnedWordBegin: "",
    returnedWordEnd: ",",
  },
  "56": {
    type: "split",
    choices: ["dern"],
    word: "son",
    completeWord: "sondern",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "57": {
    type: "whole",
    word: "um",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "58": {
    type: "split",
    choices: ["in"],
    word: "e",
    completeWord: "ein",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "59": {
    type: "whole",
    word: "Mineral",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "60": {
    type: "split",
    choices: ["ben"],
    word: "Ne",
    completeWord: "Neben",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "61": {
    type: "whole",
    word: "süß",
    returnedWordBegin: "",
    returnedWordEnd: ",",
  },
  "62": {
    type: "split",
    choices: ["ter"],
    word: "bit",
    completeWord: "bitter",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "63": {
    type: "whole",
    word: "und",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "64": {
    type: "split",
    choices: ["uer"],
    word: "sa",
    completeWord: "sauer",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "65": {
    type: "whole",
    word: "ist",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "66": {
    type: "split",
    choices: ["zig"],
    word: "sal",
    completeWord: "salzig",
    returnedWordBegin: "„",
    returnedWordEnd: "“",
    replacedWordLength: 3,
  },
  "67": {
    type: "whole",
    word: "eine",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "68": {
    type: "split",
    choices: ["er"],
    word: "d",
    completeWord: "der",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "69": {
    type: "whole",
    word: "vier",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "70": {
    type: "split",
    choices: ["igen"],
    word: "gäng",
    completeWord: "gängigen",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "71": {
    type: "whole",
    word: "Geschmacksrichtungen",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "72": {
    type: "split",
    choices: ["er"],
    word: "W",
    completeWord: "Wer",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "73": {
    type: "whole",
    word: "schon",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "74": {
    type: "split",
    choices: ["al"],
    word: "m",
    completeWord: "mal",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "75": {
    type: "whole",
    word: "eine",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "76": {
    type: "split",
    choices: ["ppe"],
    word: "Su",
    completeWord: "Suppe",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "77": {
    type: "whole",
    word: "ohne",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "78": {
    type: "split",
    choices: ["lz"],
    word: "Sa",
    completeWord: "Salz",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "79": {
    type: "whole",
    word: "gegessen",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "80": {
    type: "split",
    choices: ["at"],
    word: "h",
    completeWord: "hat",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 2,
  },
  "81": {
    type: "whole",
    word: "weiß",
    returnedWordBegin: "",
    returnedWordEnd: ",",
  },
  "82": {
    type: "split",
    choices: ["ss"],
    word: "da",
    completeWord: "dass",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "83": {
    type: "whole",
    word: "etwas",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "84": {
    type: "split",
    choices: ["lte"],
    word: "feh",
    completeWord: "fehlte",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 3,
  },
  "85": {
    type: "whole",
    word: "Sie",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "86": {
    type: "split",
    choices: ["eckte"],
    word: "schm",
    completeWord: "schmeckte",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 5,
  },
  "87": {
    type: "whole",
    word: "bestimmt",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "88": {
    type: "split",
    choices: ["lich"],
    word: "ziem",
    completeWord: "ziemlich",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "89": {
    type: "whole",
    word: "fade",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "90": {
    type: "split",
    choices: ["ch"],
    word: "Au",
    completeWord: "Auch",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "91": {
    type: "whole",
    word: "mit",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "92": {
    type: "split",
    choices: ["rst"],
    word: "Wu",
    completeWord: "Wurst",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 3,
  },
  "93": {
    type: "whole",
    word: "Brot",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "94": {
    type: "split",
    choices: ["er"],
    word: "od",
    completeWord: "oder",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "95": {
    type: "whole",
    word: "Käse",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "96": {
    type: "split",
    choices: ["nd"],
    word: "u",
    completeWord: "und",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "97": {
    type: "whole",
    word: "vielen",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "98": {
    type: "split",
    choices: ["eren"],
    word: "and",
    completeWord: "anderen",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "99": {
    type: "whole",
    word: "Speisen",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "100": {
    type: "split",
    choices: ["hält"],
    word: "ver",
    completeWord: "verhält",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "101": {
    type: "whole",
    word: "es",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "102": {
    type: "split",
    choices: ["ch"],
    word: "si",
    completeWord: "sich",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "103": {
    type: "whole",
    word: "ähnlich",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "104": {
    type: "split",
    choices: ["lz"],
    word: "Sa",
    completeWord: "Salz",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "105": {
    type: "whole",
    word: "sorgt",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "106": {
    type: "split",
    choices: ["ür"],
    word: "f",
    completeWord: "für",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "107": {
    type: "whole",
    word: "Geschmack",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "108": {
    type: "split",
    choices: ["ss"],
    word: "Da",
    completeWord: "Dass",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "109": {
    type: "whole",
    word: "Speisesalz",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "110": {
    type: "split",
    choices: ["ute"],
    word: "he",
    completeWord: "heute",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "111": {
    type: "whole",
    word: "überall",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "112": {
    type: "split",
    choices: ["o"],
    word: "s",
    completeWord: "so",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "113": {
    type: "whole",
    word: "leicht",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "114": {
    type: "split",
    choices: ["ügbar"],
    word: "verf",
    completeWord: "verfügbar",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 5,
  },
  "115": {
    type: "whole",
    word: "und",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "116": {
    type: "split",
    choices: ["cht"],
    word: "ni",
    completeWord: "nicht",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "117": {
    type: "whole",
    word: "teuer",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "118": {
    type: "split",
    choices: ["st"],
    word: "i",
    completeWord: "ist",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 2,
  },
  "119": {
    type: "whole",
    word: "war",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "120": {
    type: "split",
    choices: ["cht"],
    word: "ni",
    completeWord: "nicht",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "121": {
    type: "whole",
    word: "immer",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "122": {
    type: "split",
    choices: ["o"],
    word: "s",
    completeWord: "so",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 1,
  },
  "123": {
    type: "whole",
    word: "",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  title: "Salz nach Belieben",
  intro: "Weder Ungesalzenes noch Versalzenes schmeckt:",
  rank: "advanced",
  id: 2,
};

export default question;
