import { QuizQuestion } from "../index";

const question: QuizQuestion = {
  "1": {
    type: "whole",
    word: "",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "2": {
    type: "split",
    choices: ["as"],
    word: "D",
    completeWord: "Das",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "3": {
    type: "whole",
    word: "Corona-Virus",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "4": {
    type: "whole",
    word: "Sars-Cov-2.",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "5": {
    type: "whole",
    word: "Wer",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "6": {
    type: "split",
    choices: ["ch"],
    word: "si",
    completeWord: "sich",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "7": {
    type: "whole",
    word: "ansteckt",
    returnedWordBegin: "",
    returnedWordEnd: ",",
  },
  "8": {
    type: "split",
    choices: ["nn"],
    word: "ka",
    completeWord: "kann",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "9": {
    type: "whole",
    word: "eine",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "10": {
    type: "split",
    choices: ["were"],
    word: "sch",
    completeWord: "schwere",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "11": {
    type: "whole",
    word: "Lungenkrankheit",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "12": {
    type: "split",
    choices: ["mmen"],
    word: "beko",
    completeWord: "bekommen",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "13": {
    type: "whole",
    word: "und",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "14": {
    type: "split",
    choices: ["m"],
    word: "i",
    completeWord: "im",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "15": {
    type: "whole",
    word: "schlimmsten",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "16": {
    type: "split",
    choices: ["ll"],
    word: "Fa",
    completeWord: "Fall",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "17": {
    type: "whole",
    word: "daran",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "18": {
    type: "split",
    choices: ["rben"],
    word: "ste",
    completeWord: "sterben",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 4,
  },
  "19": {
    type: "whole",
    word: "Wissenschaftler",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "20": {
    type: "split",
    choices: ["nd"],
    word: "u",
    completeWord: "und",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "21": {
    type: "whole",
    word: "Politiker",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "22": {
    type: "split",
    choices: ["n"],
    word: "i",
    completeWord: "in",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "23": {
    type: "whole",
    word: "aller",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "24": {
    type: "split",
    choices: ["lt"],
    word: "We",
    completeWord: "Welt",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "25": {
    type: "whole",
    word: "versuchen",
    returnedWordBegin: "",
    returnedWordEnd: ",",
  },
  "26": {
    type: "split",
    choices: ["was"],
    word: "et",
    completeWord: "etwas",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "27": {
    type: "whole",
    word: "gegen",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "28": {
    type: "split",
    choices: ["ie"],
    word: "d",
    completeWord: "die",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "29": {
    type: "whole",
    word: "Ausbreitung",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "30": {
    type: "split",
    choices: ["es"],
    word: "d",
    completeWord: "des",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "31": {
    type: "whole",
    word: "Virus",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "32": {
    type: "split",
    choices: ["u"],
    word: "z",
    completeWord: "zu",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "33": {
    type: "whole",
    word: "tun",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "34": {
    type: "split",
    choices: ["n"],
    word: "I",
    completeWord: "In",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "35": {
    type: "whole",
    word: "vielen",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "36": {
    type: "split",
    choices: ["dern"],
    word: "Län",
    completeWord: "Ländern",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "37": {
    type: "whole",
    word: "haben",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "38": {
    type: "split",
    choices: ["ie"],
    word: "d",
    completeWord: "die",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "39": {
    type: "whole",
    word: "Regierungen",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "40": {
    type: "split",
    choices: ["halb"],
    word: "des",
    completeWord: "deshalb",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "41": {
    type: "whole",
    word: "strenge",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "42": {
    type: "split",
    choices: ["eln"],
    word: "Reg",
    completeWord: "Regeln",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "43": {
    type: "whole",
    word: "beschlossen",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "44": {
    type: "split",
    choices: ["ulen"],
    word: "Sch",
    completeWord: "Schulen",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "45": {
    type: "whole",
    word: "und",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "46": {
    type: "split",
    choices: ["den"],
    word: "Lä",
    completeWord: "Läden",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "47": {
    type: "whole",
    word: "wurden",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "48": {
    type: "split",
    choices: ["lossen"],
    word: "gesch",
    completeWord: "geschlossen",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 6,
  },
  "49": {
    type: "whole",
    word: "In",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "50": {
    type: "split",
    choices: ["chen"],
    word: "man",
    completeWord: "manchen",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "51": {
    type: "whole",
    word: "Ländern",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "52": {
    type: "split",
    choices: ["fen"],
    word: "dür",
    completeWord: "dürfen",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "53": {
    type: "whole",
    word: "die",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "54": {
    type: "split",
    choices: ["chen"],
    word: "Mens",
    completeWord: "Menschen",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "55": {
    type: "whole",
    word: "nicht",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "56": {
    type: "split",
    choices: ["hr"],
    word: "me",
    completeWord: "mehr",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "57": {
    type: "whole",
    word: "aus",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "58": {
    type: "split",
    choices: ["em"],
    word: "d",
    completeWord: "dem",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "59": {
    type: "whole",
    word: "Haus",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "60": {
    type: "split",
    choices: ["hen"],
    word: "ge",
    completeWord: "gehen",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 3,
  },
  "61": {
    type: "whole",
    word: "Weil",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "62": {
    type: "split",
    choices: ["ele"],
    word: "vi",
    completeWord: "viele",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "63": {
    type: "whole",
    word: "Firmen",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "64": {
    type: "split",
    choices: ["cht"],
    word: "ni",
    completeWord: "nicht",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "65": {
    type: "whole",
    word: "mehr",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "66": {
    type: "split",
    choices: ["iten"],
    word: "arbe",
    completeWord: "arbeiten",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "67": {
    type: "whole",
    word: "können",
    returnedWordBegin: "",
    returnedWordEnd: ",",
  },
  "68": {
    type: "split",
    choices: ["bt"],
    word: "gi",
    completeWord: "gibt",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "69": {
    type: "whole",
    word: "es",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "70": {
    type: "split",
    choices: ["ch"],
    word: "au",
    completeWord: "auch",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "71": {
    type: "whole",
    word: "eine",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "72": {
    type: "split",
    choices: ["ftskrise"],
    word: "Wirtscha",
    completeWord: "Wirtschaftskrise",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 8,
  },
  title: "Corona-Krise",
  intro: "Seit Anfang 2020 gibt es weltweit ein neues ansteckendes Virus:",
  rank: "basic",
  id: 1,
};

export default question;
