import { QuizQuestion } from "../index";

const question: QuizQuestion = {
  "1": {
    type: "whole",
    word: "Viele",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "2": {
    type: "split",
    choices: ["erbände"],
    word: "Kulturv",
    completeWord: "Kulturverbände",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 7,
  },
  "3": {
    type: "whole",
    word: "und",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "4": {
    type: "split",
    choices: ["erbände"],
    word: "Sportv",
    completeWord: "Sportverbände",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 7,
  },
  "5": {
    type: "whole",
    word: "haben",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "6": {
    type: "split",
    choices: ["tzt"],
    word: "je",
    completeWord: "jetzt",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "7": {
    type: "whole",
    word: "Pläne",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "8": {
    type: "split",
    choices: ["elegt"],
    word: "vorg",
    completeWord: "vorgelegt",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 5,
  },
  "9": {
    type: "whole",
    word: "damit",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "10": {
    type: "split",
    choices: ["der"],
    word: "wie",
    completeWord: "wieder",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "11": {
    type: "whole",
    word: "Veranstaltungen",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "12": {
    type: "split",
    choices: ["it"],
    word: "m",
    completeWord: "mit",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "13": {
    type: "whole",
    word: "Zuschauern",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "14": {
    type: "split",
    choices: ["lich"],
    word: "mög",
    completeWord: "möglich",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "15": {
    type: "whole",
    word: "sind",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "16": {
    type: "split",
    choices: ["as"],
    word: "D",
    completeWord: "Das",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "17": {
    type: "whole",
    word: "sind",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "18": {
    type: "split",
    choices: ["um"],
    word: "z",
    completeWord: "zum",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "19": {
    type: "whole",
    word: "Beispiel",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "20": {
    type: "split",
    choices: ["er"],
    word: "d",
    completeWord: "der",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "21": {
    type: "whole",
    word: "Deutsche",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "22": {
    type: "split",
    choices: ["-Verein"],
    word: "Bühnen",
    completeWord: "Bühnen-Verein",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 7,
  },
  "23": {
    type: "whole",
    word: "Musik-Festivals",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "24": {
    type: "split",
    choices: ["nd"],
    word: "u",
    completeWord: "und",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "25": {
    type: "whole",
    word: "der",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "26": {
    type: "split",
    choices: ["sche"],
    word: "Deut",
    completeWord: "Deutsche",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "27": {
    type: "whole",
    word: "Fußball-Bund",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "28": {
    type: "split",
    choices: ["ch"],
    word: "Na",
    completeWord: "Nach",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "29": {
    type: "whole",
    word: "den",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "30": {
    type: "split",
    choices: ["nen"],
    word: "Plä",
    completeWord: "Plänen",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "31": {
    type: "whole",
    word: "gibt",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "32": {
    type: "split",
    choices: ["s"],
    word: "e",
    completeWord: "es",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 1,
  },
  "33": {
    type: "whole",
    word: "für",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "34": {
    type: "split",
    choices: ["ossene"],
    word: "geschl",
    completeWord: "geschlossene",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 6,
  },
  "35": {
    type: "whole",
    word: "Räume",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "36": {
    type: "split",
    choices: ["ür"],
    word: "f",
    completeWord: "für",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "37": {
    type: "whole",
    word: "jeden",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "38": {
    type: "split",
    choices: ["ltungsort"],
    word: "Veransta",
    completeWord: "Veranstaltungsort",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 9,
  },
  "39": {
    type: "whole",
    word: "spezielle",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "40": {
    type: "whole",
    word: "Hygiene-",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "41": {
    type: "whole",
    word: "und",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "42": {
    type: "split",
    choices: ["sregeln"],
    word: "Lüftung",
    completeWord: "Lüftungsregeln",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 7,
  },
  "43": {
    type: "whole",
    word: "Dazu",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "44": {
    type: "split",
    choices: ["bt"],
    word: "gi",
    completeWord: "gibt",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "45": {
    type: "whole",
    word: "es",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "46": {
    type: "split",
    choices: ["kets"],
    word: "Tic",
    completeWord: "Tickets",
    returnedWordBegin: "",
    returnedWordEnd: ",",
    replacedWordLength: 4,
  },
  "47": {
    type: "whole",
    word: "die",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "48": {
    type: "split",
    choices: ["ur"],
    word: "n",
    completeWord: "nur",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "49": {
    type: "whole",
    word: "auf",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "50": {
    type: "split",
    choices: ["ne"],
    word: "ei",
    completeWord: "eine",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "51": {
    type: "whole",
    word: "bestimmte",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "52": {
    type: "split",
    choices: ["son"],
    word: "Per",
    completeWord: "Person",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "53": {
    type: "whole",
    word: "ausgestellt",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "54": {
    type: "split",
    choices: ["den"],
    word: "wer",
    completeWord: "werden",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 3,
  },
  "55": {
    type: "whole",
    word: "Außerdem",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "56": {
    type: "split",
    choices: ["ss"],
    word: "mu",
    completeWord: "muss",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "57": {
    type: "whole",
    word: "ein",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "58": {
    type: "split",
    choices: ["nischer"],
    word: "medizi",
    completeWord: "medizinischer",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 7,
  },
  "59": {
    type: "whole",
    word: "Mund-Nasen-Schutz",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "60": {
    type: "split",
    choices: ["agen"],
    word: "getr",
    completeWord: "getragen",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "61": {
    type: "whole",
    word: "werden",
    returnedWordBegin: "",
    returnedWordEnd: ".",
  },
  "62": {
    type: "split",
    choices: ["rdem"],
    word: "Auße",
    completeWord: "Außerdem",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 4,
  },
  "63": {
    type: "whole",
    word: "sollen",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "64": {
    type: "split",
    choices: ["hauer"],
    word: "Zusc",
    completeWord: "Zuschauer",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 5,
  },
  "65": {
    type: "whole",
    word: "vor",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "66": {
    type: "split",
    choices: ["der"],
    word: "je",
    completeWord: "jeder",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 3,
  },
  "67": {
    type: "whole",
    word: "Veranstaltung",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "68": {
    type: "split",
    choices: ["uf"],
    word: "a",
    completeWord: "auf",
    returnedWordBegin: "",
    returnedWordEnd: "",
    replacedWordLength: 2,
  },
  "69": {
    type: "whole",
    word: "das",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "70": {
    type: "whole",
    word: "Corona-Virus",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "71": {
    type: "whole",
    word: "getestet",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  "72": {
    type: "split",
    choices: ["den"],
    word: "wer",
    completeWord: "werden",
    returnedWordBegin: "",
    returnedWordEnd: ".",
    replacedWordLength: 3,
  },
  "73": {
    type: "whole",
    word: "",
    returnedWordBegin: "",
    returnedWordEnd: "",
  },
  title: "Öffnungs-Pläne für die Kultur",
  intro: "In der Corona-Pandemie finden keine Kultur-Veranstaltungen statt.",
  rank: "basic",
  id: 2,
};

export default question;
